# Jekyll configuration
name: Protein-Sequence-Motif-Extractor
description: The Protein Sequence Motif Extractor reads a fasta file or tab delimited file containing protein sequences, then looks for the specified motif in each protein sequence.
url: https://pnnl-comp-mass-spec.github.io/Protein-Sequence-Motif-Extractor/

# Google Analytics
google_analytics: G-LXXKP1N66C
